### ISSUE TITLE
Questions about point clouds

### ISSUE THREAD

**Issue by XIN499** [yizzfz/MiliPoint#3]
Hello, I'm just a beginner of the area and I'm a little confused of your impressive project.
Is your raw data the 2D coordinates of the point cloud or the 3D coordinates? When I read the paper, I thought the model was dealing with the xyz coordinates of the point cloud, however, what is provided in the code and the raw data files seem to be 2d coordinates?
If it is 2D coordinates, is a certain dimension directly discarded or other special processing is done?

**Comment by yizzfz** [comment]
The point cloud data provided are indeed 3D coordinates. Which part of the code are you referring to?
