### ISSUE TITLE
mmWave Radar data collection

### ISSUE THREAD

**Issue by Gbouna** [yizzfz/MiliPoint#4]
Thank you for your work. Could you kindly share the procedure or link you used to read data from the mmwave radar board? I want to understand the process of reading data from the mmwave board so that I can test it with my own data. 
Thank you.

**Comment by yizzfz** [comment]
The simplest way would be the out-of-the-box [demo](https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/3.6.0/) provided by TI. I have developed my own Python toolchain for customized data reading and processing, available in [my other repo](https://github.com/yizzfz/mmRadarVision). Feel free to explore it, but be prepared with minimal documentation, as I am not actively maintaining it.
