### ISSUE TITLE
Action collection problem

### ISSUE THREAD

**Issue by loushilong** [yizzfz/MiliPoint#5]
Thank you very much for your great work, I am a beginner in this field. You mentioned in the paper that the point cloud frame rate is 24 frames per second, and the time of one action is 1-2 seconds, so one action is about 50 frames. I checked the action_label.npy file and found that some actions last around 200 frames. When you collect actions, is each action collected repeatedly? If so, how many times do you repeat each move?
Looking forward to your reply, thank you very much.

**Comment by yizzfz** [comment]
> "The video lasts around 30 minutes with 49 different actions; each action lasts 30 seconds with a 10 seconds break in between. "

So the maximum number of frames per action per person would be 30 * 24 frames, but many of them were labelled -1, due to warm-ups, breaks, incorrect movements, etc. The YouTube link provided in the paper may help in understanding the actions.
